# 4.8: Grouping Data & Aggregating Variables

In [1]:
# Importing libraries
import pandas as pd
import numpy as np
import os

In [2]:
path = r'C:\Users\Brichaelle\01-08-2023 Instacart Basket Analysis'

In [3]:
ords_prods_merge = pd.read_pickle(os.path.join(path, '02 Data','Prepared Data', 'orders_products_variables.pkl'))

## Table of Contents

1 - Aggregating Variables

2 - Loyalty Flag

3 - Spending Flag

4 - Order Frequency Flag

5 - Exporting

## 1. Aggregating Variables

In [4]:
# Aggregated mean
ords_prods_merge.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
1                16.423480
2                18.308000
3                18.141973
4                18.755308
5                16.432216
6                17.439753
7                18.206801
8                16.247133
9                16.881621
10               21.053865
11               17.160888
12               16.798667
13               17.593560
14               17.710767
15               17.153661
16               18.603668
17               16.684490
18               20.197809
19               18.134171
20               17.433797
21               23.511099

#### a subset, as its name will only supply insights based on a select number of rows and will not give results of the big picture. running the syntax on the full set will give the most accurate results while looking at everything on a grand scale

## 2. Loyalty flag

In [6]:
ords_prods_merge['max_order'] = ords_prods_merge.groupby(['user_id'])['order_number'].transform(np.max)

In [7]:
ords_prods_merge.head(15)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day_loc,max_order
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,prior,28,6,11,3.0,5,0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,32
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,prior,30,6,17,20.0,1,1,both,Mid-range product,Regularly busy,Regularly busy,Average orders,32
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,prior,2,0,21,6.0,20,0,both,Mid-range product,Busiest day,Busiest day one,Average orders,5
3,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,prior,3,4,17,9.0,11,1,both,Mid-range product,Least busy,Slowest day two,Average orders,3
5,1,Chocolate Sandwich Cookies,61,19,5.8,1871483,825,prior,3,2,14,30.0,2,0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,8
6,1,Chocolate Sandwich Cookies,61,19,5.8,1290456,910,prior,12,3,10,30.0,1,0,both,Mid-range product,Regularly busy,Slowest day one,Most orders,12
7,1,Chocolate Sandwich Cookies,61,19,5.8,369558,1052,prior,10,1,20,19.0,1,0,both,Mid-range product,Regularly busy,Busiest day two,Average orders,19
8,1,Chocolate Sandwich Cookies,61,19,5.8,589712,1052,prior,15,1,12,15.0,2,1,both,Mid-range product,Regularly busy,Busiest day two,Most orders,19
9,1,Chocolate Sandwich Cookies,61,19,5.8,497193,1480,prior,36,3,13,7.0,1,0,both,Mid-range product,Regularly busy,Slowest day one,Most orders,43
10,1,Chocolate Sandwich Cookies,61,19,5.8,1727826,1480,prior,38,4,13,7.0,3,1,both,Mid-range product,Least busy,Slowest day two,Most orders,43
11,1,Chocolate Sandwich Cookies,61,19,5.8,2694698,1480,prior,39,2,12,12.0,4,1,both,Mid-range product,Regularly busy,Regularly busy,Most orders,43
12,1,Chocolate Sandwich Cookies,61,19,5.8,3171753,1494,prior,6,3,10,2.0,8,0,both,Mid-range product,Regularly busy,Slowest day one,Most orders,12
16,1,Chocolate Sandwich Cookies,61,19,5.8,374436,1540,prior,5,1,21,6.0,9,1,both,Mid-range product,Regularly busy,Busiest day two,Average orders,28
19,1,Chocolate Sandwich Cookies,61,19,5.8,2365998,1540,prior,8,1,23,6.0,6,1,both,Mid-range product,Regularly busy,Busiest day two,Fewest orders,28
21,1,Chocolate Sandwich Cookies,61,19,5.8,2799665,1540,prior,14,1,14,7.0,10,1,both,Mid-range product,Regularly busy,Busiest day two,Most orders,28

In [8]:
ords_prods_merge.loc[ords_prods_merge['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [9]:
ords_prods_merge.loc[(ords_prods_merge['max_order'] <= 40) & (ords_prods_merge['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'

In [10]:
ords_prods_merge.loc[ords_prods_merge['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [11]:
ords_prods_merge['loyalty_flag'].value_counts(dropna = False)

Regular customer    12268123
Loyal customer       8059057
New customer         4360393
Name: loyalty_flag, dtype: int64

### Customer types' spending habits

In [13]:
ords_prods_merge.groupby('loyalty_flag').agg({'prices': ['mean', 'min', 'max']})

                     prices
                       mean  min      max
loyalty_flag
Loyal customer    10.269076  1.0  99999.0
New customer      13.229825  1.0  99999.0
Regular customer  12.472123  1.0  99999.0

## 3. Spending Flag by mean

In [14]:
ords_prods_merge['mean_prices'] = ords_prods_merge.groupby(['user_id'])['prices'].transform(np.mean)

In [15]:
ords_prods_merge.head(15)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,eval_set,order_number,order_dow,...,add_to_cart_order,reordered,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day_loc,max_order,loyalty_flag,mean_prices
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,prior,28,6,...,5,0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,32,Regular customer,6.896000
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,prior,30,6,...,1,1,both,Mid-range product,Regularly busy,Regularly busy,Average orders,32,Regular customer,6.896000
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,prior,2,0,...,20,0,both,Mid-range product,Busiest day,Busiest day one,Average orders,5,New customer,8.071613
3,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,prior,3,4,...,11,1,both,Mid-range product,Least busy,Slowest day two,Average orders,3,New customer,4.864103
5,1,Chocolate Sandwich Cookies,61,19,5.8,1871483,825,prior,3,2,...,2,0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,8,New customer,6.223077
6,1,Chocolate Sandwich Cookies,61,19,5.8,1290456,910,prior,12,3,...,1,0,both,Mid-range product,Regularly busy,Slowest day one,Most orders,12,Regular customer,6.788889
7,1,Chocolate Sandwich Cookies,61,19,5.8,369558,1052,prior,10,1,...,1,0,both,Mid-range product,Regularly busy,Busiest day two,Average orders,19,Regular customer,6.895000
8,1,Chocolate Sandwich Cookies,61,19,5.8,589712,1052,prior,15,1,...,2,1,both,Mid-range product,Regularly busy,Busiest day two,Most orders,19,Regular customer,6.895000
9,1,Chocolate Sandwich Cookies,61,19,5.8,497193,1480,prior,36,3,...,1,0,both,Mid-range product,Regularly busy,Slowest day one,Most orders,43,Loyal customer,4.982258
10,1,Chocolate Sandwich Cookies,61,19,5.8,1727826,1480,prior,38,4,...,3,1,both,Mid-range product,Least busy,Slowest day two,Most orders,43,Loyal customer,4.982258
11,1,Chocolate Sandwich Cookies,61,19,5.8,2694698,1480,prior,39,2,...,4,1,both,Mid-range product,Regularly busy,Regularly busy,Most orders,43,Loyal customer,4.982258
12,1,Chocolate Sandwich Cookies,61,19,5.8,3171753,1494,prior,6,3,...,8,0,both,Mid-range product,Regularly busy,Slowest day one,Most orders,12,Regular customer,6.435593
16,1,Chocolate Sandwich Cookies,61,19,5.8,374436,1540,prior,5,1,...,9,1,both,Mid-range product,Regularly busy,Busiest day two,Average orders,28,Regular customer,6.649049
19,1,Chocolate Sandwich Cookies,61,19,5.8,2365998,1540,prior,8,1,...,6,1,both,Mid-range product,Regularly busy,Busiest day two,Fewest orders,28,Regular customer,6.649049
21,1,Chocolate Sandwich Cookies,61,19,5.8,2799665,1540,prior,14,1,...,10,1,both,Mid-range product,Regularly busy,Busiest day two,Most orders,28,Regular customer,6.649049

In [22]:
ords_prods_merge.loc[ords_prods_merge['mean_prices'] > 10, 'spending_flag'] = 'Low spender'

In [23]:
ords_prods_merge.loc[ords_prods_merge['mean_prices'] <= 10, 'spending_flag'] = 'High spender'

In [24]:
ords_prods_merge['spending_flag'].value_counts(dropna = False)

High spender    24220686
Low spender       466887
Name: spending_flag, dtype: int64

## 4. Order frequency flag by median

In [25]:
ords_prods_merge['order_frequency'] = ords_prods_merge.groupby(['user_id'])['days_since_prior_order'].transform(np.median)

In [27]:
ords_prods_merge.loc[ords_prods_merge['order_frequency'] > 20, 'order_frequency_flag'] = 'Non-frequent customer'

In [28]:
ords_prods_merge.loc[(ords_prods_merge['order_frequency'] <= 20) & (ords_prods_merge['order_frequency'] > 10), 'order_frequency_flag'] = 'Regular customer'

In [29]:
ords_prods_merge.loc[ords_prods_merge['order_frequency'] <= 10, 'order_frequency_flag'] = 'Frequent customer'

In [30]:
ords_prods_merge.head(15)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,eval_set,order_number,order_dow,...,price_range_loc,busiest_day,busiest_days,busiest_period_of_day_loc,max_order,loyalty_flag,mean_prices,spending_flag,order_frequency,order_frequency_flag
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,prior,28,6,...,Mid-range product,Regularly busy,Regularly busy,Most orders,32,Regular customer,6.896000,High spender,8.0,Frequent customer
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,prior,30,6,...,Mid-range product,Regularly busy,Regularly busy,Average orders,32,Regular customer,6.896000,High spender,8.0,Frequent customer
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,prior,2,0,...,Mid-range product,Busiest day,Busiest day one,Average orders,5,New customer,8.071613,High spender,8.0,Frequent customer
3,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,prior,3,4,...,Mid-range product,Least busy,Slowest day two,Average orders,3,New customer,4.864103,High spender,9.0,Frequent customer
5,1,Chocolate Sandwich Cookies,61,19,5.8,1871483,825,prior,3,2,...,Mid-range product,Regularly busy,Regularly busy,Most orders,8,New customer,6.223077,High spender,19.0,Regular customer
6,1,Chocolate Sandwich Cookies,61,19,5.8,1290456,910,prior,12,3,...,Mid-range product,Regularly busy,Slowest day one,Most orders,12,Regular customer,6.788889,High spender,3.5,Frequent customer
7,1,Chocolate Sandwich Cookies,61,19,5.8,369558,1052,prior,10,1,...,Mid-range product,Regularly busy,Busiest day two,Average orders,19,Regular customer,6.895000,High spender,10.0,Frequent customer
8,1,Chocolate Sandwich Cookies,61,19,5.8,589712,1052,prior,15,1,...,Mid-range product,Regularly busy,Busiest day two,Most orders,19,Regular customer,6.895000,High spender,10.0,Frequent customer
9,1,Chocolate Sandwich Cookies,61,19,5.8,497193,1480,prior,36,3,...,Mid-range product,Regularly busy,Slowest day one,Most orders,43,Loyal customer,4.982258,High spender,7.0,Frequent customer
10,1,Chocolate Sandwich Cookies,61,19,5.8,1727826,1480,prior,38,4,...,Mid-range product,Least busy,Slowest day two,Most orders,43,Loyal customer,4.982258,High spender,7.0,Frequent customer
11,1,Chocolate Sandwich Cookies,61,19,5.8,2694698,1480,prior,39,2,...,Mid-range product,Regularly busy,Regularly busy,Most orders,43,Loyal customer,4.982258,High spender,7.0,Frequent customer
12,1,Chocolate Sandwich Cookies,61,19,5.8,3171753,1494,prior,6,3,...,Mid-range product,Regularly busy,Slowest day one,Most orders,12,Regular customer,6.435593,High spender,3.0,Frequent customer
16,1,Chocolate Sandwich Cookies,61,19,5.8,374436,1540,prior,5,1,...,Mid-range product,Regularly busy,Busiest day two,Average orders,28,Regular customer,6.649049,High spender,7.0,Frequent customer
19,1,Chocolate Sandwich Cookies,61,19,5.8,2365998,1540,prior,8,1,...,Mid-range product,Regularly busy,Busiest day two,Fewest orders,28,Regular customer,6.649049,High spender,7.0,Frequent customer
21,1,Chocolate Sandwich Cookies,61,19,5.8,2799665,1540,prior,14,1,...,Mid-range product,Regularly busy,Busiest day two,Most orders,28,Regular customer,6.649049,High spender,7.0,Frequent customer

In [31]:
ords_prods_merge['order_frequency_flag'].value_counts(dropna = False)

Frequent customer        16796957
Regular customer          5297614
Non-frequent customer     2593002
Name: order_frequency_flag, dtype: int64

## 5. Exporting

In [32]:
ords_prods_merge.to_pickle(os.path.join(path, '02 Data','Prepared Data', 'orders_products_grouping.pkl'))